name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: update
      run: sudo apt-get update
    - name: install gcov
      run: sudo apt-get install gcov
    - name: install valgrind
      run: sudo apt-get install valgrind
    - name: make
      run: make
