name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: list
      run: ls
    - name: make
      run: cd app && make all

  cppcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: update
      run: sudo apt-get update
    - name: install cppcheck
      run: sudo apt-get install cppcheck
    - name: run cppcheck
      run: cd app && make cppcheck

  valgrind:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: update
      run: sudo apt-get update
    - name: install valgrind
      run: sudo apt-get install valgrind
    - name: run valgrind
      run: cd app && make valgrind

  sanitizer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: run sanitizer
      run: cd app && make sanitizer

  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install gcovr
      run: sudo pip3 install gcovr
    - name: run gcov and gcovr
      run: cd app && make cov
